#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../../", import.meta.url));

function writeLauncher(relative: string, target: string): void {
  const file = path.join(root, relative);
  const specifier = path.relative(path.dirname(file), path.join(root, target)).replaceAll("\\", "/");
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `#!/usr/bin/env node\n// Generated by the TypeScript build.\nawait import(${JSON.stringify(specifier.startsWith(".") ? specifier : `./${specifier}`)});\n`, { mode: 0o755 });
  fs.chmodSync(file, 0o755);
}

writeLauncher("index.js", "build/index.js");
writeLauncher("bin/bevy-mcp.js", "build/bin/bevy-mcp.js");
const shellLauncher = path.join(root, "scripts", "rebuild-all-indexes.sh");
fs.writeFileSync(shellLauncher, '#!/bin/sh\n# Generated by the TypeScript build.\nexec node "$(dirname "$0")/../build/scripts/rebuild-all-indexes.mjs" "$@"\n', { mode: 0o755 });
fs.chmodSync(shellLauncher, 0o755);
for (const directory of ["scripts", "test"]) {
  for (const entry of fs.readdirSync(path.join(root, "build", directory), { withFileTypes: true })) {
    if (entry.isFile() && entry.name.endsWith(".mjs")) {
      writeLauncher(`${directory}/${entry.name}`, `build/${directory}/${entry.name}`);
    }
  }
}
